### PR TITLE
fix: stop exporting a TS file as `"main"` field in `package.json`

### PR DESCRIPTION
**Pull request by u9g**
same issue as https://github.com/octokit/openapi-types.ts/pull/45 applies here and is an easy fix :)

### CODE REVIEW

**Comment by andywer** [comment]
So maybe #12 wasn't such a good idea after all… 😅

Thanks for the fix!

**Comment by u9g** [comment]
Thanks for such a quick reply :)

**Comment by eliellis** [comment]
Hi @andywer. Would it be at all possible to get this fix out into an NPM release? Not too big of a rush, as I was able to do the workaround described in #14 for now. Thanks so much for all your hard work. Loving threads.js too. 😄

**Comment by hongaar** [comment]
Just bumped into this issue now (see https://github.com/hongaar/bandersnatch/pull/295), would be wonderful if this could be released to NPM. Let me know if I can help with anything (e.g. I could create a PR to add a `semantic-release` GitHub actions workflow to this repository if you'd be open to that?)

**Pull request merged**
